ask_tgarifullin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse, Http404
from questions import views
def err404(request):
	raise Http404("PageNotFound")

urlpatterns = [
    url(r'^test_gunicorn/?$', views.test_gu),
    url(r'^$', views.index, name='index'),
    url(r'^hot/$', views.hot, name='hot'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^question/', include('questions.urls')),
    url(r'^userset/', views.userset, name='userset'),
    url(r'^ask/', views.ask, name='ask'),
    # url(r'^profile/', views.profile, name='profile'),
    url(r'^tag/(?P<tag_word>(\w|(\+|#|\-)+)+)/$', views.tag, name='tag_detail'),
    url(r'^', err404),
]

questions/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^(?P<question_id>[0-9]+)/$', views.question_detail, name='question_detail'),
#    url(r'^$', views.onequestion),
#    url(r'^about$', AboutView.as_view(), name='about'),
]

questions/models.py
from __future__ import unicode_literals
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser, UserManager
from django.db.models import Count

# Create your models here.

class MyUserManager(UserManager):
    def get_top_N(self,N):
        return self.order_by('-rating')[0:N]



class User(AbstractUser):
    upload = models.ImageField(default='static/img/ava.png', upload_to='%Y/%m/%d/', verbose_name=u"Аватар")
    rating = models.IntegerField(default=0, verbose_name=u"Рейтинг")
    objects = MyUserManager()


class QuestionManager(models.Manager):
    def top_questions(self):
        return self.filter(is_active=True).order_by('-status__likesNum')
    def new_questions(self):
        return self.filter(is_active=True).order_by('-create_date')
    def questions_tag(self, tag_word):
        return self.filter(is_active=True, tags__title__iexact=tag_word).order_by('-status__likesNum')
    def set_like(self, q_id, d_like):
        obj = Question.objects.get(id=q_id)
        stat = obj.status
        oldLikesNum = stat.likesNum
        stat.likesNum = oldLikesNum + d_like
        stat.save()


class Category(models.Model):
    title = models.CharField(max_length=120, unique=True, verbose_name=u"Заголовок категории")

    def __str__(self):
        return self.title


class TagManager(models.Manager):
    def get_top_N(self,N):
        return self.values('title').annotate(num_questions=Count('question')).order_by('-num_questions')[0:N]


class Tag(models.Model):
    title = models.CharField(max_length=120, unique=True, verbose_name=u"Заголовок тега")
    objects = TagManager()

    def __str__(self):
        return self.title


class Status(models.Model):
    viewsNum = models.IntegerField(default=0, verbose_name=u"Количество просмотров")
    likesNum = models.IntegerField(default=0, verbose_name=u"Количество лайков")


class Question(models.Model):
    author = models.ForeignKey(User)
    title = models.CharField(max_length=120, verbose_name=u"Заголовок вопроса")
    text = models.TextField(verbose_name=u"Полное описание вопроса")
    create_date = models.DateTimeField(default=datetime.now, verbose_name=u"Время создания вопроса")
    is_active = models.BooleanField(default=True, verbose_name=u"Доступность вопроса")
    tags = models.ManyToManyField(Tag, blank=True)
    category = models.ForeignKey(Category, blank=True)
    status = models.OneToOneField(Status)
    objects = QuestionManager()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-create_date']


class AnswerManager(models.Manager):
    def set_like(self, a_id, d_like):
        obj = Answer.objects.get(id=a_id)
        oldRating = obj.rating
        obj.rating = oldRating + d_like
        obj.save()


class Answer(models.Model):
    author = models.ForeignKey(User)
    text = models.TextField(verbose_name=u"Текст ответа")
    create_date = models.DateTimeField(default=datetime.now, verbose_name=u"Время создания ответа")
    is_active = models.BooleanField(default=True, verbose_name=u"Доступность ответа")
    is_correct = models.BooleanField(default=False, verbose_name=u"Правильность ответа")
    question = models.ForeignKey(Question)
    rating = models.IntegerField(default=0, verbose_name=u"Рейтинг")
    objects = AnswerManager()

questions/forms.py
from django import forms
from django.contrib import auth
from questions import models

class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20, required=True)
    password = forms.CharField(label='Password', widget=forms.PasswordInput, required=True)

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = auth.authenticate(username=username,
                                           password=password)
            if self.user_cache is None:
                raise forms.ValidationError(u'Неверное имя или пароль', code=11)

        return self.cleaned_data



class UserCreationForm(forms.Form):
    username = forms.CharField(label='Login', max_length=20, required=True)
    email = forms.EmailField(label='E-mail', required=True)
    nickname = forms.CharField(label='Nick name', max_length=20, required=True)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(label='Password(repeat)', widget=forms.PasswordInput, required=True)
    avatar=forms.ImageField(label='Avatar',
        widget=forms.FileInput (
            attrs={'class': 'form-control-file'}
        ), required=False)

    def clean_username(self):
        name = self.cleaned_data.get("username")
        user = models.User.objects.filter(username=name)[:1]
        if user:
            raise forms.ValidationError(u'Такой логин уже занят', code=21)
        return name

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(u'Пароли не совпадают', code=22)
        return password2

    def save(self, commit=True):
        name = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password1')
        user = models.User.objects.create_user(name, email, password)
        user.first_name = self.cleaned_data.get('nickname')
        if self.cleaned_data.get('avatar'):
            user.upload = self.cleaned_data['avatar']
        user.save()
        return user


class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = ['username', 'email', 'upload']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = ['text']

    def save(self, qId, userId):
        text = self.cleaned_data['text']
        answer = models.Answer(author_id = userId, text = text, question_id = qId)
        answer.save()
        return answer.id


class AddQuestionForm(forms.Form):
    title = forms.CharField(label='Title', max_length=50, required=True)
    category = forms.CharField(label='Category', max_length=50, required=True)
    text = forms.CharField(widget=forms.Textarea, label='Text', required=True)
    tags = forms.CharField(label='Tags', max_length=50, required=True)

    def clean_tags(self):
        tags = self.cleaned_data["tags"].split(',')
        if len(tags) > 3:
            raise forms.ValidationError(u'Введите не более трех тегов', code=21)
        for tag in tags:
            tag = tag.lower().lstrip(' \t').rstrip(' \t')
            if tag is '':
                raise forms.ValidationError(u'Пустые теги', code=21)
        return tags

    def save(self, request):
        stat = models.Status()
        stat.save()
        catName = self.cleaned_data['category'].lower().lstrip(' \t').rstrip(' \t')
        try:
            cat = models.Category.objects.get(title=catName)
        except models.Category.DoesNotExist:
            cat = None
        if cat is None:
            cat = models.Category(title=catName)
            cat.save()
        question = models.Question(author_id=request.user.id, title=self.cleaned_data['title'], text=self.cleaned_data['text'], category=cat,
                     status=stat)
        question.save()
        tags = self.cleaned_data["tags"].split(',')
        if len(tags) > 3:
            tags = tags[:3]
        for tag in tags:
            tag = tag.lower().lstrip(' \t').rstrip(' \t')
            try:
                newTag = models.Tag.objects.get(title = tag)
            except models.Tag.DoesNotExist:
                newTag = None
            if newTag is None:
                newTag = models.Tag(title=tag)
                newTag.save()
            question.tags.add(newTag)
        question.save()
        return question.id

questions/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from questions import forms
from questions.models import Question, Answer, Tag, User
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse

from django.contrib import auth

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from faker import lorem
from random import shuffle

def test_gu(request):
    text_lst = []
    msg = ''
    if request.method == 'GET':
        req_lists = request.GET.lists()
    if request.method == 'POST':
        req_lists = request.POST.lists()
    for key, lst in req_lists:
        if key == 'csrfmiddlewaretoken':
            continue
        for word in lst:
            msg = msg + key + '=' + word
            text_lst.append(msg)
            msg = ''
    return render(request, 'test_gu.html', {'text': text_lst})



def paginate(objects, request):
    limit = 5
    page_num = 1
    if request.method == 'GET':
        page_num = int(request.GET.get('page', 1))
        limit = int(request.GET.get('limit', 5))
    p = Paginator(objects, limit)
    p.limiturl = 'limit='+str(limit)
    try:
        pageN = p.page(page_num)
    except PageNotAnInteger:
        pageN = p.page(1)
    except EmptyPage:
        pageN = p.page(p.num_pages)
    object_page = pageN.object_list
    return object_page, pageN


def is_set_like(request):
    like = None
    if request.method == 'POST':
        like = request.POST.get('like')
    if like:
        req_type = request.POST.get('type')
        if req_type == 'question':
            q_id=request.POST.get('id')
            if like == 'p':
                Question.objects.set_like(q_id, 1)
            if like == 'm':
                Question.objects.set_like(q_id, -1)
        if req_type == 'answer':
            a_id = request.POST.get('id')
            if like == 'p':
                Answer.objects.set_like(a_id, 1)
            if like == 'm':
                Answer.objects.set_like(a_id, -1)


def get_top_tags():
    return Tag.objects.get_top_N(5)

def get_top_users():
    return User.objects.get_top_N(5)


# Create your views here.

def index(request):
    ctx = dict()
    qlist = Question.objects.new_questions()
    page_qlist, pageN = paginate(qlist, request)
    is_set_like(request)
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['questions'] = page_qlist
    ctx['page'] = pageN
    ctx['tag_list'] = tag_list
    return render(request, 'new.html', ctx)

def hot(request):
    ctx = dict()
    qlist = Question.objects.top_questions()
    page_qlist, pageN = paginate(qlist, request)
    is_set_like(request)
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['questions'] = page_qlist
    ctx['page'] = pageN
    ctx['tag_list'] = tag_list
    return render(request, 'hot.html', ctx)

def tag(request, tag_word):
    ctx = dict()
    q_tag_list = Question.objects.questions_tag(tag_word)
    is_set_like(request)
    page_qlist, pageN = paginate(q_tag_list, request)
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['questions'] = page_qlist
    ctx['page'] = pageN
    ctx['tag_list'] = tag_list
    ctx['tag_word'] = tag_word
    return render(request, 'tag.html', ctx)

def question_detail(request, question_id):
    ctx = dict()
    post = get_object_or_404(Question, id=question_id)
    is_set_like(request)
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['post'] = post
    ctx['tag_list'] = tag_list
    if request.POST:
        form = forms.AnswerForm(request.POST)
        if form.is_valid():
            answId = form.save(question_id, request.user.id)
            return redirect('./#'+str(answId))
    else:
        form = forms.AnswerForm()
    ctx['form'] = form
    return render(request, 'question_detail.html', ctx)

def signin(request):
    ctx = dict()
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['title'] = 'ASK.me-sign in'
    ctx['tag_list'] = tag_list
    if request.POST:
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user is not None and user.is_active:
                auth.login(request, user)
                redir = request.GET.get('next', '/')
                return redirect(redir)
    else:
        form = forms.LoginForm
    ctx['form'] = form
    return render(request, 'signin.html', ctx)

@login_required
def logout(request):
    auth.logout(request)
    return redirect('/')

def signup(request):
    ctx = dict()
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['title'] = 'ASK.me-sign up'
    ctx['tag_list'] = tag_list
    if request.POST:
        form = forms.UserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            return redirect('/')
    else:
        form = forms.UserCreationForm()
    ctx['form'] = form
    return render(request, 'signup.html', ctx)

#def onequestion(request):
#    return render(request, 'onequestion.html', {'title': 'ASK.me - One question'})

@login_required
def userset(request):
    ctx = dict()
    tag_list = get_top_tags()
    user_list = get_top_users()
    ctx['user_list'] = user_list
    ctx['title'] = 'ASK.me-user settings'
    ctx['tag_list'] = tag_list
    if request.POST:
        user = User.objects.get(id=request.user.id)
        form = forms.ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('./')
    else:
        user = User.objects.get(id = request.user.id)
        form = forms.ProfileForm(instance=user)
    ctx['form'] = form
    return render(request, 'userset.html', ctx)

@login_required
def ask(request):
    ctx = dict()
    tag_list = get_top_tags()
    user_list = get_top_users()
    
    ctx['user_list'] = user_list
    ctx['title'] = 'ASK.me-Ask'
    ctx['tag_list'] = tag_list
    if request.POST:
        form = forms.AddQuestionForm(request.POST)
        if form.is_valid():
            qId = form.save(request)
            return redirect(reverse('question_detail', kwargs={'question_id': qId}))
    else:
        form = forms.AddQuestionForm()
    ctx['form'] = form
    return render(request, 'ask.html', ctx)
# def profile(request):
#     prof = request.user.username
#     print(prof)
#
#     return render(request, 'userset.html')
#

templates/questions/hot.html
{% extends "base.html" %}

{% block title %}Hot-ASK.me{% endblock %}

{% block content %}

          <div class="row quest_head"><div class="col-md-5 col-sm-12">
            <h1>Hot Questions</h1></div>
            <div class="col-3 HotQ">
            <a href="{% url 'index' %}">New Questions</a>
          </div></div>
           <div class="row pages"> <h4>
                <ul>
                    <li>Сортировать по:</li>
                    <li><a href="{% url 'hot' %}?limit=5">5</a></li>
                    <li><a href="{% url 'hot' %}?limit=10">10</a></li>
                    <li><a href="{% url 'hot' %}?limit=20">20</a></li>
                </ul></h4>
            </div>
              {% for question in questions %}
                  {% include "./question.html" %}
              {% endfor %}

          <div class="pages">
          <ul>
            <li>
              {% if page.has_previous %}
                  <a href="{% url 'hot' %}?page={{ page.previous_page_number }}&{{ page.paginator.limiturl }}">previous</a>
              {% endif %}
            </li>
            <li>
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </li>
            <li>
              {% if page.has_next %}
                  <a href="{% url 'hot' %}?page={{ page.next_page_number }}&{{ page.paginator.limiturl }}">next</a>
              {% endif %}
            </li>
          </ul>
        </div>


{% endblock %}

templates/questions/new.html
{% extends "base.html" %}

{% block title %}ASK.me{% endblock %}

{% block content %}

          <div class="row quest_head"><div class="col-md-5 col-sm-12">
            <h1>New Questions</h1></div>
            <div class="col-md-3 col-sm-12 HotQ">
            <a href="{% url 'hot' %}">Hot Questions</a>
            </div></div>
            <div class="row pages"> <h4>
                <ul>
                    <li>Сортировать по:</li>
                    <li><a href="{% url 'index' %}?limit=5">5</a></li>
                    <li><a href="{% url 'index' %}?limit=10">10</a></li>
                    <li><a href="{% url 'index' %}?limit=20">20</a></li>
                </ul></h4>
            </div>

              {% for question in questions %}
                  {% include "./question.html" %}
              {% endfor %}

          <div class="pages">
          <ul>
            <li>
              {% if page.has_previous %}
                  <a href="{% url 'index' %}?page={{ page.previous_page_number }}&{{ page.paginator.limiturl }}">previous</a>
              {% endif %}
            </li>
            <li>
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </li>
            <li>
              {% if page.has_next %}
                  <a href="{% url 'index' %}?page={{ page.next_page_number }}&{{ page.paginator.limiturl }}">next</a>
              {% endif %}
            </li>
          </ul>
        </div>


{% endblock %}

templates/questions/question_detail.html
{% extends "base.html" %}

{% block title %} {{post.title}} {% endblock %}

{% block content %}

        <article class="lmarg20">
            <header>
              <h1 class="one_question"><u>{{ post.title }}</u></h1>
            </header>
            <div class="row">
              <div class='col-12 col-md-3 quest'>
                <img src="/{{ post.author.upload.url }}" width="90%">
              </div>
              <div class='col-12 col-md-9'>
                {{ post.text }}
              </div>
            </div>
            <div class="foot">
              <div class="quest_foot">
               <div class="row" style="margin-left: 15px; margin-top: 5px; display: flex;">
                  <div class="col-md-3 col-sm-12 ">
                    <form action=" " method="GET">
                      <div class="row rating">
                       <div class="col-md-4 ratCell"><button><img src="/static/img/plus.ico" width="100%"></button></div>
                       <div class="col-md-4 ratCell">{{ post.status.likesNum }}</div>
                       <div class="col-md-4 ratCell"><button><img src="/static/img/minus.ico" width="100%"></button></div>
                      </div>
                    </form>
                  </div>
                 <div class="col-md-9 col-sm-12">Tags:
                 {% for tag in post.tags.all %}
                        <u><a href="{% url 'tag_detail' tag.title %}">{{ tag.title }}</a></u>
                    {% endfor %}
                 </div>
                </div>
              </footer>
            </div>
            <hr>
          </article>
          <div class="answers">

              {% for answer in post.answer_set.all %}
                  {% include "./answer.html" %}
              {% endfor %}

          </div>

          <hr class="my_hr">
            <div class="new_answer">
            <form action=" " method="POST">
             <div class="forma">
              <div class="row regPoint">
                <div class="col-md-9">
                   <textarea name="comment" cols="100" rows="6" required class="border"></textarea>
                </div>
              </div>
        {% csrf_token %}
              <div class="answ_btn">
                <button class="submit">
                  Ответить
                </button>
              </div>
              </div>
              </form>
          </div>


{% endblock %}

templates/questions/tag.html
{% extends "../base.html" %}

{% block title %}ASK.me - Tag: {{ tag_word }}{% endblock %}

{% block content %}

          <div class="row quest_head">
            <h1>Tag: {{ tag_word }}</h1>
            </div>
            <div class="row" style="margin-left: 20px">
                Результатов: {{ page.paginator.count }}</div>
            <div class="row pages"> <h4>
                <ul>
                    <li>Сортировать по:</li>
                    <li><a href="{% url 'tag_detail' tag_word %}?limit=5">5</a></li>
                    <li><a href="{% url 'tag_detail' tag_word %}?limit=10">10</a></li>
                    <li><a href="{% url 'tag_detail' tag_word %}?limit=20">20</a></li>
                </ul></h4></div>

              {% for question in questions %}
                  {% include "./question.html" %}
              {% endfor %}


          <div class="pages">
          <ul>
            <li>
              {% if page.has_previous %}
                  <a href="{% url 'tag_detail' tag_word %}?page={{ page.previous_page_number }}&{{ page.paginator.limiturl }}">previous</a>
              {% endif %}
            </li>
            <li>
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </li>
            <li>
              {% if page.has_next %}
                  <a href="{% url 'tag_detail' tag_word %}?page={{ page.next_page_number }}&{{ page.paginator.limiturl }}">next</a>
              {% endif %}
          </ul>
        </div>


{% endblock %}